### ISSUE TITLE
Broken NSF link

### ISSUE THREAD

**Issue by sgpearse** [NCAR/jekyll-koru#3] opened 2019-07-31 15:36 UTC
At https://www.vapor.ucar.edu/, the NSF logo is a broken link.

![](https://user-images.githubusercontent.com/814885/62170590-263a7480-b2e9-11e9-9427-dd94434056fc.png)

**Comment by geinosky** [comment] 2020-07-21 20:58
Duplicate of #1.

**Closed as completed by geinosky** 2020-07-21 20:58 UTC
